name: Build STM32 IMU Firmware

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install dependencies
        run: sudo apt install gcc-arm-none-eabi -y

      - name: CMake configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build

      - name: Build
        run: cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: stm32-imu-attitude-firmware
          path: |
            build/stm32_imu_attitude.elf
            build/stm32_imu_attitude.hex
            build/stm32_imu_attitude.bin
            build/stm32_imu_attitude.map
          if-no-files-found: error
